### ISSUE TITLE
What container runtime would you like to pick?

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/hp#9]
A brief list of options:

* `runc` -- a few requires, it's not easy to run containers
* `atomic` -- requires python and has a lot of dependencies
* `cri-o` -- work in progress
* `docker` -- 'de facto' standard, fast release-cycle, complex software

**Comment by contyk** [comment]
During today's meeting we basically agreed to include `runc` in `platform`, with the possibility of dropping a container runtime entirely later on.

The reason is it is the only long-term stable runtime we have. The rest is either incomplete, is being developed at a too fast pace or is not available on all architectures. For these reasons, they're not suitable for `platform` and should be shipped in separate modules.

**Comment by contyk** [comment]
Addressed in `ea9cce7`.
